### PR TITLE
Added hdr10+ detection in file view and in the videoplayer

### PR DESCRIPTION
**Pull request by frodo19**
Added hdr10+ detection by filename in file view,  and in the video player/video-OSD.

The kodi hdrtype not recognize the hdr10+ , added when filename exist.

### CODE REVIEW

**Comment by frodo19** [comment]
The monochrome images need rename. There is hdr10+ image, need rename to hdr10plus. And add a hdr10 image.
The colorful is ok.

**Comment by DenDyGH** [comment]
There's no need to use variations with `..__--` also one `$VAR` should be enough.
Like this:
```
    <variable name="Image_VideoPlayer_HDRCodec">
        <value condition="String.IsEqual(ListItem.HdrType,dolbyvision)">flags/$INFO[Skin.String(Icons)]/other/dolbyvision.png</value>
        <value condition="String.IsEqual(ListItem.HdrType,hdr10)">flags/$INFO[Skin.String(Icons)]/other/hdr10.png</value>
        <value condition="String.IsEqual(ListItem.HdrType,hlg)">flags/$INFO[Skin.String(Icons)]/other/hlg.png</value>
        <value condition="String.Contains(ListItem.FileNameAndPath,hdr10plus) | String.Contains(ListItem.FileNameAndPath,12bit) | [VideoPlayer.IsFullscreen + [String.Contains(Player.FileNameAndPath,hdr10plus) | String.Contains(Player.FileNameAndPath,12bit)]]">flags/$INFO[Skin.String(Icons)]/other/hdr10plus.png</value>
        <value>flags/$INFO[Skin.String(Icons)]/other/HDR.png</value>
    </variable>
```

Do you think adding 12bit is a good idea? Because I'm not sure about that.

**Comment by frodo19** [comment]
Maybe you can delete that 12Bit, I'v seen some older release with that.

**Comment by frodo19** [comment]
Thank you

**Pull request merged**
