### PR TITLE
Add CD Spin to VideoOSD

### PR DESCRIPTION
**Pull request by frodo19**
Added rotating disc-art to the movie info, improved the rotating music CD > when no disc-art available. With one cd-art-mask, we can use the thumb for one "fake cd-art".
 Also added pop-up animation there too.

Hint:  maybe you can you improve later, the music-CD pop-up animation, to animate all times, when open the music info during play.  Currently just pop-up once. 
The movie disc-art pop up repeatedly when reopen the info during play.

thx

### CODE REVIEW

**Comment by DenDyGH** [comment]
Hmm, MusicOSD is weird, no idea what's causing it. So it will stay like this for now.

**Review by frodo19 — COMMENTED** [review]
With your corrections, the Discart in the video osd visible earlier than the slide effect, and seen in the poster, sometimes. Thats why i added delay. 
My coreelec amb6+ is powered, maybe quicker, but you can[ see in this video](https://mega.nz/file/CtMjkJaL#z30Y34WzwwtbwKdHI42dmsana8xXdfsaM5Lqqmpt2PQ)

**Comment by DenDyGH** [comment]
You are right, my bad.
`Fade` animation for whole seekbar group takes `350ms` so `370 delay` should be safe.
Also removed `fade` for `WindowClose` because there's `fade` animation for whole group so no need to double it.
https://github.com/DenDyGH/skin.arctic.zephyr.2.resurrection.mod/commit/9c9071d537a5ec34c870be5cc7d71cbc03753d7f

**Comment by frodo19** [comment]
Thank you.

**Pull request merged**
